// Realistic Indian context mock dataset for Grab Rentals Operations & Admin portals

export const initialVehicles = [
  {
    id: "VEH-001",
    registrationNumber: "TN 01 AB 1234",
    model: "Toyota Innova Crysta",
    category: "SUV",
    seatingCapacity: 7,
    fuelType: "Diesel",
    transmission: "Automatic",
    status: "AVAILABLE",
    vendorId: "VND-101",
    vendorName: "Royal Travels Chennai",
    currentLocation: "T. Nagar, Chennai",
    mileage: 42150,
    insuranceExpiry: "2026-11-20",
    fitnessExpiry: "2027-05-14",
    permitType: "All India Tourist Permit",
    acType: "Dual Zone AC",
  },
  {
    id: "VEH-002",
    registrationNumber: "TN 38 BK 9021",
    model: "Maruti Suzuki Ertiga ZXi",
    category: "SUV",
    seatingCapacity: 7,
    fuelType: "Petrol / CNG",
    transmission: "Manual",
    status: "ON_DUTY",
    vendorId: "VND-102",
    vendorName: "Kovai Fleet Solutions",
    currentLocation: "Gandhipuram, Coimbatore",
    mileage: 28900,
    insuranceExpiry: "2026-10-15",
    fitnessExpiry: "2027-04-10",
    permitType: "Tamil Nadu State Permit",
    acType: "Standard AC",
  },
  {
    id: "VEH-003",
    registrationNumber: "KA 05 MJ 8821",
    model: "Force Urbania 12-Seater",
    category: "Van",
    seatingCapacity: 12,
    fuelType: "Diesel",
    transmission: "Manual",
    status: "AVAILABLE",
    vendorId: "VND-103",
    vendorName: "Bangalore Express Transports",
    currentLocation: "Electronic City, Bangalore",
    mileage: 18400,
    insuranceExpiry: "2027-01-30",
    fitnessExpiry: "2027-08-15",
    permitType: "All India Tourist Permit",
    acType: "Roof Mounted Individual AC",
  },
  {
    id: "VEH-004",
    registrationNumber: "KL 07 CD 4512",
    model: "Force Tempo Traveller 17-Seater",
    category: "Van",
    seatingCapacity: 17,
    fuelType: "Diesel",
    transmission: "Manual",
    status: "ON_DUTY",
    vendorId: "VND-104",
    vendorName: "Malabar Bus Lines",
    currentLocation: "Vyttila, Kochi",
    mileage: 63100,
    insuranceExpiry: "2026-12-05",
    fitnessExpiry: "2027-03-22",
    permitType: "South Zone Tourist Permit",
    acType: "Full Ducted AC",
  },
  {
    id: "VEH-005",
    registrationNumber: "TN 09 CS 7766",
    model: "BharatBenz 36-Seater AC Coach",
    category: "Bus",
    seatingCapacity: 36,
    fuelType: "Diesel",
    transmission: "Manual",
    status: "AVAILABLE",
    vendorId: "VND-101",
    vendorName: "Royal Travels Chennai",
    currentLocation: "Koyambedu Hub, Chennai",
    mileage: 91200,
    insuranceExpiry: "2026-09-30",
    fitnessExpiry: "2027-06-18",
    permitType: "All India Tourist Permit",
    acType: "Central Climate Control",
  },
  {
    id: "VEH-006",
    registrationNumber: "TN 59 DA 3311",
    model: "Toyota Fortuner 4x4",
    category: "SUV",
    seatingCapacity: 7,
    fuelType: "Diesel",
    transmission: "Automatic",
    status: "AVAILABLE",
    vendorId: "VND-105",
    vendorName: "Southern Fleet Hub",
    currentLocation: "Mattuthavani, Madurai",
    mileage: 34500,
    insuranceExpiry: "2027-02-14",
    fitnessExpiry: "2027-07-01",
    permitType: "All India Tourist Permit",
    acType: "Dual Zone Climate Control",
  },
  {
    id: "VEH-007",
    registrationNumber: "TN 02 XZ 5544",
    model: "Maruti Dzire Tour S",
    category: "Sedan",
    seatingCapacity: 5,
    fuelType: "CNG",
    transmission: "Manual",
    status: "AVAILABLE",
    vendorId: "VND-101",
    vendorName: "Royal Travels Chennai",
    currentLocation: "Airport Hub, Chennai",
    mileage: 51200,
    insuranceExpiry: "2026-11-10",
    fitnessExpiry: "2027-01-20",
    permitType: "Tamil Nadu State Permit",
    acType: "Standard AC",
  },
  {
    id: "VEH-008",
    registrationNumber: "KA 01 EK 9900",
    model: "Volvo 45-Seater Multi-Axle",
    category: "Bus",
    seatingCapacity: 45,
    fuelType: "Diesel",
    transmission: "Automatic",
    status: "MAINTENANCE",
    vendorId: "VND-103",
    vendorName: "Bangalore Express Transports",
    currentLocation: "Yeshwanthpur Depot, Bangalore",
    mileage: 124500,
    insuranceExpiry: "2026-08-15",
    fitnessExpiry: "2026-11-30",
    permitType: "All India Tourist Permit",
    acType: "Air Suspension Luxury AC",
  },
];

export const initialDrivers = [
  {
    id: "DRV-201",
    name: "Murugan S.",
    phone: "+91 98401 23456",
    badgeNumber: "TN01-2018-9941",
    licenseNumber: "TN-0120150008472",
    experienceYears: 11,
    status: "AVAILABLE",
    rating: 4.9,
    vendorId: "VND-101",
    vendorName: "Royal Travels Chennai",
    currentLocation: "Chennai Central",
    languages: ["Tamil", "English", "Telugu"],
    tripsCompleted: 432,
    badgeValidTill: "2028-06-30",
  },
  {
    id: "DRV-202",
    name: "Rajesh Kumar",
    phone: "+91 94432 87654",
    badgeNumber: "TN38-2019-3321",
    licenseNumber: "TN-3820170004123",
    experienceYears: 8,
    status: "ON_DUTY",
    rating: 4.8,
    vendorId: "VND-102",
    vendorName: "Kovai Fleet Solutions",
    currentLocation: "Coimbatore Airport",
    languages: ["Tamil", "Malayalam", "English"],
    tripsCompleted: 310,
    badgeValidTill: "2027-11-15",
  },
  {
    id: "DRV-203",
    name: "Abdul Rahman",
    phone: "+91 99800 11223",
    badgeNumber: "KA05-2016-7788",
    licenseNumber: "KA-0520140009812",
    experienceYears: 14,
    status: "AVAILABLE",
    rating: 4.95,
    vendorId: "VND-103",
    vendorName: "Bangalore Express Transports",
    currentLocation: "Majestic, Bangalore",
    languages: ["Kannada", "Hindi", "English", "Tamil"],
    tripsCompleted: 620,
    badgeValidTill: "2029-01-20",
  },
  {
    id: "DRV-204",
    name: "Vignesh P.",
    phone: "+91 97455 66778",
    badgeNumber: "KL07-2020-1199",
    licenseNumber: "KL-0720190003411",
    experienceYears: 6,
    status: "ON_DUTY",
    rating: 4.7,
    vendorId: "VND-104",
    vendorName: "Malabar Bus Lines",
    currentLocation: "Ernakulam North, Kochi",
    languages: ["Malayalam", "Tamil", "English"],
    tripsCompleted: 195,
    badgeValidTill: "2028-04-10",
  },
  {
    id: "DRV-205",
    name: "Suresh Babu",
    phone: "+91 98421 99881",
    badgeNumber: "TN59-2017-5544",
    licenseNumber: "TN-5920160007812",
    experienceYears: 12,
    status: "AVAILABLE",
    rating: 4.85,
    vendorId: "VND-105",
    vendorName: "Southern Fleet Hub",
    currentLocation: "Periyar Bus Stand, Madurai",
    languages: ["Tamil", "English"],
    tripsCompleted: 480,
    badgeValidTill: "2028-10-05",
  },
];

export const initialBookings = [
  {
    id: "BK-8091",
    customerName: "Priya Sundaram",
    customerPhone: "+91 98840 55123",
    customerEmail: "priya.sundaram@techcorp.in",
    serviceType: "Outstation Round Trip",
    pickupLocation: "Anna Nagar, Chennai",
    dropLocation: "Ooty Botanical Gardens",
    startDate: "2026-09-26 06:00 AM",
    endDate: "2026-09-28 09:00 PM",
    durationDays: 3,
    distanceKm: 1140,
    vehicleCategory: "SUV",
    preferredVehicle: "Toyota Innova Crysta",
    assignedVehicleId: null,
    assignedVehicleNumber: null,
    assignedDriverId: null,
    assignedDriverName: null,
    status: "PENDING_ALLOCATION",
    fare: 26500,
    advancePaid: 5000,
    balanceAmount: 21500,
    paymentStatus: "PARTIAL",
    paymentMethod: "UPI / Razorpay",
    vendorId: "VND-101",
    vendorName: "Royal Travels Chennai",
    specialInstructions: "Family trip with senior citizen. Need AC and polite English/Tamil speaking chauffeur.",
    createdAt: "2026-09-24 10:30 AM",
    urgency: "HIGH",
  },
  {
    id: "BK-8092",
    customerName: "Anand Mahadevan",
    customerPhone: "+91 98401 77332",
    customerEmail: "anand.m@chennaienterprises.com",
    serviceType: "Airport Transfer",
    pickupLocation: "ITC Grand Chola, Guindy, Chennai",
    dropLocation: "Chennai International Airport T2",
    startDate: "2026-09-24 04:30 PM",
    endDate: "2026-09-24 06:00 PM",
    durationDays: 1,
    distanceKm: 12,
    vehicleCategory: "Sedan",
    preferredVehicle: "Maruti Dzire Tour S",
    assignedVehicleId: "VEH-007",
    assignedVehicleNumber: "TN 02 XZ 5544",
    assignedDriverId: "DRV-201",
    assignedDriverName: "Murugan S.",
    status: "ASSIGNED",
    fare: 1450,
    advancePaid: 1450,
    balanceAmount: 0,
    paymentStatus: "PAID",
    paymentMethod: "Corporate Credit Card",
    vendorId: "VND-101",
    vendorName: "Royal Travels Chennai",
    specialInstructions: "VIP executive arrival. Keep vehicle spotlessly clean.",
    createdAt: "2026-09-24 09:15 AM",
    urgency: "MEDIUM",
  },
  {
    id: "BK-8089",
    customerName: "Vikramaditya Rao",
    customerPhone: "+91 99805 44112",
    customerEmail: "vikram.rao@itconsultancy.co",
    serviceType: "Outstation Multi-Day",
    pickupLocation: "Indiranagar, Bangalore",
    dropLocation: "Coorg Heritage Resort, Madikeri",
    startDate: "2026-09-24 06:00 AM",
    endDate: "2026-09-25 08:00 PM",
    durationDays: 2,
    distanceKm: 560,
    vehicleCategory: "Van",
    preferredVehicle: "Force Urbania 12-Seater",
    assignedVehicleId: "VEH-003",
    assignedVehicleNumber: "KA 05 MJ 8821",
    assignedDriverId: "DRV-203",
    assignedDriverName: "Abdul Rahman",
    status: "EN_ROUTE",
    tripMilestone: "Passing Mysore Ring Road",
    fare: 22800,
    advancePaid: 8000,
    balanceAmount: 14800,
    paymentStatus: "PARTIAL",
    paymentMethod: "Net Banking",
    vendorId: "VND-103",
    vendorName: "Bangalore Express Transports",
    specialInstructions: "Team outing group of 9 people.",
    createdAt: "2026-09-23 03:00 PM",
    urgency: "NORMAL",
  },
  {
    id: "BK-8085",
    customerName: "Meenakshi Iyer",
    customerPhone: "+91 94440 12890",
    customerEmail: "meenakshi.iyer@gmail.com",
    serviceType: "Temple Tour",
    pickupLocation: "Madurai Junction",
    dropLocation: "Rameswaram Temple & Return",
    startDate: "2026-09-23 05:00 AM",
    endDate: "2026-09-23 10:00 PM",
    durationDays: 1,
    distanceKm: 340,
    vehicleCategory: "SUV",
    preferredVehicle: "Toyota Fortuner",
    assignedVehicleId: "VEH-006",
    assignedVehicleNumber: "TN 59 DA 3311",
    assignedDriverId: "DRV-205",
    assignedDriverName: "Suresh Babu",
    status: "COMPLETED",
    fare: 8900,
    advancePaid: 8900,
    balanceAmount: 0,
    paymentStatus: "PAID",
    paymentMethod: "UPI",
    vendorId: "VND-105",
    vendorName: "Southern Fleet Hub",
    specialInstructions: "Completed on schedule with 5-star customer review.",
    createdAt: "2026-09-22 08:00 AM",
    urgency: "NORMAL",
  },
  {
    id: "BK-8082",
    customerName: "Naveen Thomas",
    customerPhone: "+91 97441 33221",
    customerEmail: "naveen.t@keralatourism.org",
    serviceType: "Kerala Hill Station Circuit",
    pickupLocation: "Fort Kochi",
    dropLocation: "Munnar Tea Estates & Return",
    startDate: "2026-09-22 07:00 AM",
    endDate: "2026-09-24 07:00 PM",
    durationDays: 3,
    distanceKm: 420,
    vehicleCategory: "Van",
    preferredVehicle: "Force Tempo Traveller 17-Seater",
    assignedVehicleId: "VEH-004",
    assignedVehicleNumber: "KL 07 CD 4512",
    assignedDriverId: "DRV-204",
    assignedDriverName: "Vignesh P.",
    status: "COMPLETED",
    fare: 28500,
    advancePaid: 28500,
    balanceAmount: 0,
    paymentStatus: "PAID",
    paymentMethod: "Credit Card",
    vendorId: "VND-104",
    vendorName: "Malabar Bus Lines",
    specialInstructions: "UK tourist delegate party.",
    createdAt: "2026-09-20 11:20 AM",
    urgency: "NORMAL",
  },
  {
    id: "BK-8078",
    customerName: "Siddharth Menon",
    customerPhone: "+91 98450 67891",
    customerEmail: "siddharth.m@startupgrid.io",
    serviceType: "Corporate Event Transport",
    pickupLocation: "Whitefield, Bangalore",
    dropLocation: "KIAL Airport Terminal 1",
    startDate: "2026-09-21 02:00 PM",
    endDate: "2026-09-21 04:30 PM",
    durationDays: 1,
    distanceKm: 45,
    vehicleCategory: "Sedan",
    preferredVehicle: "Maruti Dzire",
    assignedVehicleId: null,
    assignedVehicleNumber: null,
    assignedDriverId: null,
    assignedDriverName: null,
    status: "CANCELLED",
    fare: 1850,
    advancePaid: 1850,
    balanceAmount: 0,
    paymentStatus: "REFUNDED",
    paymentMethod: "UPI",
    vendorId: "VND-103",
    vendorName: "Bangalore Express Transports",
    specialInstructions: "Flight got cancelled due to weather; customer requested cancellation.",
    createdAt: "2026-09-21 10:00 AM",
    urgency: "NORMAL",
  },
];

export const initialVendors = [
  {
    id: "VND-101",
    name: "Royal Travels Chennai",
    contactPerson: "K. Subramanian",
    phone: "+91 98410 88990",
    email: "operations@royaltravelschennai.in",
    city: "Chennai",
    address: "42, Jawaharlal Nehru Road, Koyambedu, Chennai - 600107",
    status: "APPROVED",
    fleetCount: 24,
    driverCount: 28,
    activeBookings: 8,
    commissionRate: 12,
    gstNumber: "33AAACR4412K1Z9",
    rating: 4.8,
    joinedDate: "2024-03-15",
  },
  {
    id: "VND-102",
    name: "Kovai Fleet Solutions",
    contactPerson: "D. Palanisamy",
    phone: "+91 94422 11445",
    email: "contact@kovaifleet.com",
    city: "Coimbatore",
    address: "18, Cross Cut Road, Gandhipuram, Coimbatore - 641012",
    status: "APPROVED",
    fleetCount: 16,
    driverCount: 18,
    activeBookings: 4,
    commissionRate: 10,
    gstNumber: "33AABCK8871M1Z4",
    rating: 4.6,
    joinedDate: "2024-06-20",
  },
  {
    id: "VND-103",
    name: "Bangalore Express Transports",
    contactPerson: "Manjunath Gowda",
    phone: "+91 99860 33441",
    email: "ops@bangaloreexpress.in",
    city: "Bangalore",
    address: "88, Hosur Main Road, Madiwala, Bangalore - 560068",
    status: "APPROVED",
    fleetCount: 32,
    driverCount: 35,
    activeBookings: 11,
    commissionRate: 15,
    gstNumber: "29AAGCB5521L1ZP",
    rating: 4.9,
    joinedDate: "2023-11-10",
  },
  {
    id: "VND-104",
    name: "Malabar Bus Lines",
    contactPerson: "Shaji Mathew",
    phone: "+91 94470 55667",
    email: "info@malabarbuslines.com",
    city: "Kochi",
    address: "12/404, Sahodaran Ayyappan Road, Kadavanthra, Kochi - 682020",
    status: "APPROVED",
    fleetCount: 19,
    driverCount: 22,
    activeBookings: 5,
    commissionRate: 12,
    gstNumber: "32AAMMB3399D1ZQ",
    rating: 4.7,
    joinedDate: "2024-01-18",
  },
  {
    id: "VND-105",
    name: "Southern Fleet Hub",
    contactPerson: "S. Alagarsamy",
    phone: "+91 98422 44771",
    email: "booking@southernfleethub.com",
    city: "Madurai",
    address: "7, Alagar Kovil Main Road, Tallakulam, Madurai - 625002",
    status: "APPROVED",
    fleetCount: 14,
    driverCount: 15,
    activeBookings: 3,
    commissionRate: 10,
    gstNumber: "33AAHCS7712E1Z8",
    rating: 4.65,
    joinedDate: "2024-08-01",
  },
  {
    id: "VND-106",
    name: "Pondy Coastline Travels",
    contactPerson: "Jean-Pierre Arul",
    phone: "+91 98940 12345",
    email: "contact@pondycoastline.fr",
    city: "Pondicherry",
    address: "24, Rue Dumas, White Town, Puducherry - 605001",
    status: "PENDING_APPROVAL",
    fleetCount: 8,
    driverCount: 9,
    activeBookings: 0,
    commissionRate: 12,
    gstNumber: "34AABCP9911K1Z2",
    rating: 0,
    joinedDate: "2026-09-22",
  },
];

export const initialCustomers = [];


export const initialOperationsUsers = [];


export const pricingMatrix = [
  {
    category: "Sedan",
    examples: "Maruti Dzire, Toyota Etios, Honda Amaze",
    capacity: "4 Passengers",
    baseFare: 1200,
    baseIncludedKm: 40,
    perKmRate: 14,
    perHourWaitingRate: 120,
    driverBattaPerDay: 400,
    nightSurcharge: 250,
  },
  {
    category: "SUV",
    examples: "Toyota Innova Crysta, Maruti Ertiga, Mahindra XUV700",
    capacity: "6-7 Passengers",
    baseFare: 2200,
    baseIncludedKm: 80,
    perKmRate: 20,
    perHourWaitingRate: 180,
    driverBattaPerDay: 500,
    nightSurcharge: 350,
  },
  {
    category: "Van",
    examples: "Force Urbania, Force Tempo Traveller (12-17s)",
    capacity: "12-17 Passengers",
    baseFare: 4500,
    baseIncludedKm: 100,
    perKmRate: 28,
    perHourWaitingRate: 250,
    driverBattaPerDay: 700,
    nightSurcharge: 500,
  },
  {
    category: "Bus",
    examples: "BharatBenz Coach, Volvo Multi-Axle (36-45s)",
    capacity: "36-45 Passengers",
    baseFare: 11000,
    baseIncludedKm: 150,
    perKmRate: 52,
    perHourWaitingRate: 500,
    driverBattaPerDay: 1200,
    nightSurcharge: 900,
  },
];

export const refundRequests = [
  {
    id: "REF-401",
    bookingId: "BK-8078",
    customerName: "Siddharth Menon",
    originalFare: 1850,
    requestedAmount: 1850,
    cancellationFee: 150,
    approvedRefund: 1700,
    reason: "Flight cancelled by airline due to heavy rainfall. Customer cancelled 4 hrs in advance.",
    status: "PROCESSING",
    requestedAt: "2026-09-21 11:30 AM",
    mode: "Original Payment (Razorpay UPI)",
  },
  {
    id: "REF-399",
    bookingId: "BK-8052",
    customerName: "Radha Krishnan",
    originalFare: 9200,
    requestedAmount: 4000,
    cancellationFee: 0,
    approvedRefund: 4000,
    reason: "Trip cut short by 1 day due to medical emergency.",
    status: "COMPLETED",
    requestedAt: "2026-09-19 04:15 PM",
    mode: "Net Banking IMPS",
  },
];

export const complaintsList = [
  {
    id: "CMP-501",
    bookingId: "BK-8071",
    customerName: "Mahesh Swaminathan",
    phone: "+91 98402 11993",
    category: "Vehicle Air Conditioning",
    severity: "MEDIUM",
    status: "IN_REVIEW",
    assignedTo: "Karthik Narayanan (Ops)",
    summary: "Rear AC blower in Tempo Traveller was blowing ambient air during Madurai trip.",
    createdAt: "2026-09-23 06:10 PM",
  },
  {
    id: "CMP-502",
    bookingId: "BK-8064",
    customerName: "Farhan Sait",
    phone: "+91 99801 44556",
    category: "Driver Punctuality",
    severity: "LOW",
    status: "RESOLVED",
    assignedTo: "Divya Bharathi (Ops)",
    summary: "Driver reached pickup 20 minutes late due to road diversion in OMR.",
    createdAt: "2026-09-22 09:40 AM",
  },
];

export const customerRequests = [
  {
    id: "REQ-701",
    bookingId: "BK-8091",
    customerName: "Priya Sundaram",
    requestType: "Add Extra Stop",
    details: "Add 45-minute stopover at Coonoor Tea Factory on the way to Ooty.",
    status: "PENDING_APPROVAL",
    requestedAt: "2026-09-24 11:00 AM",
  },
  {
    id: "REQ-702",
    bookingId: "BK-8089",
    customerName: "Vikramaditya Rao",
    requestType: "Extend Duration",
    details: "Customer requested extending trip by half day for late checkout in Madikeri.",
    status: "APPROVED",
    requestedAt: "2026-09-24 09:30 AM",
  },
];

export const vendorCoordinations = [
  {
    id: "VCOORD-901",
    vendorId: "VND-101",
    vendorName: "Royal Travels Chennai",
    issueType: "Vehicle Inspection",
    details: "Innova Crysta TN 01 AB 1234 scheduled for monthly safety inspection.",
    priority: "HIGH",
    status: "OPEN",
    updatedAt: "2026-09-24 08:30 AM",
  },
  {
    id: "VCOORD-902",
    vendorId: "VND-103",
    vendorName: "Bangalore Express Transports",
    issueType: "Fastag Toll Reconciliation",
    details: "Bangalore-Mysore Expressway toll balance update required for 3 vehicles.",
    priority: "MEDIUM",
    status: "IN_PROGRESS",
    updatedAt: "2026-09-23 04:00 PM",
  },
];

export const auditLogs = [
  {
    id: "AUD-801",
    timestamp: "2026-09-24 12:45:10",
    userId: "admin@grabrentals.com",
    userName: "System Administrator",
    action: "UPDATE_PRICING",
    module: "Pricing Matrix",
    ipAddress: "103.21.144.92",
    details: "Updated SUV per-km rate from ₹19 to ₹20",
  },
  {
    id: "AUD-802",
    timestamp: "2026-09-24 11:20:45",
    userId: "ops@grabrentals.com",
    userName: "Karthik Narayanan (Ops)",
    action: "ALLOCATE_DRIVER",
    module: "Operations Dispatch",
    ipAddress: "182.73.18.24",
    details: "Allocated driver DRV-201 (Murugan S.) to booking BK-8092",
  },
  {
    id: "AUD-803",
    timestamp: "2026-09-24 09:35:12",
    userId: "admin@grabrentals.com",
    userName: "System Administrator",
    action: "APPROVE_VENDOR",
    module: "Vendor Management",
    ipAddress: "103.21.144.92",
    details: "Approved vendor VND-105 (Southern Fleet Hub) with 10% commission",
  },
  {
    id: "AUD-804",
    timestamp: "2026-09-23 16:15:20",
    userId: "admin@grabrentals.com",
    userName: "System Administrator",
    action: "AUTHORIZE_REFUND",
    module: "Refunds",
    ipAddress: "103.21.144.92",
    details: "Authorized refund REF-399 of ₹4,000 to Radha Krishnan",
  },
];

export const platformLocations = [
  { id: "LOC-1", city: "Chennai", state: "Tamil Nadu", hubs: 5, activeVehicles: 48, status: "ACTIVE" },
  { id: "LOC-2", city: "Bangalore", state: "Karnataka", hubs: 6, activeVehicles: 62, status: "ACTIVE" },
  { id: "LOC-3", city: "Coimbatore", state: "Tamil Nadu", hubs: 3, activeVehicles: 28, status: "ACTIVE" },
  { id: "LOC-4", city: "Kochi", state: "Kerala", hubs: 4, activeVehicles: 34, status: "ACTIVE" },
  { id: "LOC-5", city: "Madurai", state: "Tamil Nadu", hubs: 2, activeVehicles: 21, status: "ACTIVE" },
  { id: "LOC-6", city: "Pondicherry", state: "Puducherry", hubs: 2, activeVehicles: 15, status: "ACTIVE" },
];

export const platformServices = [
  { id: "SRV-1", name: "Outstation Round Trip", code: "OUTSTATION_ROUND", description: "Multi-day outstation city-to-city travel with designated chauffeur.", active: true },
  { id: "SRV-2", name: "One Way Drop", code: "ONE_WAY", description: "Intercity or airport direct drop with no return charge.", active: true },
  { id: "SRV-3", name: "Airport Transfer", code: "AIRPORT_XFER", description: "Point-to-point airport pickup and drops with flight tracking.", active: true },
  { id: "SRV-4", name: "Local City Hourly Package", code: "LOCAL_HOURLY", description: "City usage for business meetings or sightseeing (4hr/40km or 8hr/80km).", active: true },
  { id: "SRV-5", name: "Tour & Pilgrimage Circuit", code: "PILGRIMAGE_TOUR", description: "Curated multi-stop spiritual or vacation circuits with buses and vans.", active: true },
];

export const initialReviews = [
  {
    id: "REV-101",
    bookingId: "BK-8085",
    customerName: "Meenakshi Iyer",
    rating: 5,
    comment: "Chauffeur Suresh Babu was extremely courteous and drove very smoothly on the Madurai-Rameswaram highway. The Fortuner was in mint condition!",
    createdAt: "2026-09-23 11:30 PM",
    status: "PUBLISHED",
  },
  {
    id: "REV-102",
    bookingId: "BK-8082",
    customerName: "Naveen Thomas",
    rating: 5,
    comment: "Our UK guests thoroughly enjoyed the Munnar trip. Driver Vignesh was polite and knew all the viewpoints. Force Traveller was very comfortable.",
    createdAt: "2026-09-24 09:00 AM",
    status: "PUBLISHED",
  },
];
